### PR TITLE
Add possibility to change the shell binary

### PR DESCRIPTION
**Pull request by villuorav**
Basically I have a shared hosting site, that has well, 
```
[vhost68584ssh@procyon ~]$ which bash
/usr/local/bin/bash
[vhost68584ssh@procyon ~]$ /bin/bash
-bash: /bin/bash: No such file or directory
```
which means no shell-cookie-sugar-coated-sweetness for me :(

But as I am not actually a PHP person, I need some tips and pointers on how to get started with this functional testing point
"3. Please make sure to include functional tests for your changes."
Examples maybe :)

### CODE REVIEW

**Comment by villu164** [comment]
@schlessera, let me know what you think

**Comment by villuorav** [comment]
@schlessera, let me know what you think (sorry, previous comment was under wrong account)

**Comment by schlessera** [comment]
@villuorav I'm sorry, I don't really understand what the goal of this issue is. Are you trying to add a new functionality that lets you change the default shell of a user? There is already a Unix tool for that called `chsh`. Also, this would be out of scope for WP-CLI.

Can you explain in more detail what you're after?

**Comment by schlessera** [comment]
@villuorav Are you still up for working on this?

**Comment by villuorav** [comment]
Hi, sorry, completely forgot about this one

**Comment by schlessera** [comment]
Thanks for the PR, @villuorav !

**Pull request merged**
